#!/bin/sh
set -e

PAST_VERSION_NUMBERS="1.0.0 1.0.0.1 1.0.0.2 1.0.0.3"

echo "Checking for running TS-UNIX services before removal..."

for version in $PAST_VERSION_NUMBERS; do
    if systemctl list-units --type=service --no-pager | grep -q "ts-unix-$version"; then
        systemctl stop ts-unix-$version || true
    else
        echo "Skipping ts-unix-$version, service not found."
    fi
done

exit 0
